# Generated by Django 5.1.1 on 2024-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settinng',
            new_name='Setting',
        ),
    ]
