# Generated by Django 5.1.1 on 2024-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('photo', models.ImageField(upload_to='employee_photo/')),
                ('bio', models.TextField(verbose_name='Краткое описание или биография')),
            ],
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
