# Generated by Django 5.1.1 on 2024-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_employee_delete_galery_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='galery/')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Setting',
        ),
    ]
